import { Emoji, ES, EG, EP } from "../types/types";

export const emojis: Emoji[] = [
    // Faces - Smileys and emotions
    ES("😀", "grinning face happy smile joy laugh cheerful positive"),
    ES("😃", "grinning face with big eyes happy excited thrilled delighted"),
    ES("😄", "grinning face with smiling eyes happy joy laugh cheerful"),
    ES("😁", "beaming face with smiling eyes happy proud pleased satisfied"),
    ES("😆", "grinning squinting face laugh funny joke hilarious haha"),
    ES("🥹", "face holding back tears emotional touched moved grateful"),
    ES("😅", "grinning face with sweat relieved phew close-call nervous"),
    ES("😂", "face with tears of joy lol haha rofl lmao hilarious"),
    ES("🤣", "rolling on the floor laughing hysterical lmao rofl lol"),
    ES("🥲", "smiling face with tear bittersweet happy sad nostalgia"),
    ES("☺️", "smiling face content pleased warm friendly kind"),
    ES("😊", "smiling face with smiling eyes happy friendly shy sweet blushing"),
    ES("😇", "smiling face with halo innocent angel good pure"),
    ES("🙂", "slightly smiling face ok satisfied neutral fine"),
    ES("🙃", "upside-down face silly playful sarcasm irony weird"),
    ES("😉", "winking face flirty joke kidding friendly hint"),
    ES("😌", "relieved face calm relaxed content peaceful"),
    ES("😍", "smiling face with heart-eyes love adore crush infatuated"),
    ES("🥰", "smiling face with hearts love adoration affection loving"),
    ES("😘", "face blowing a kiss love affection flirty xoxo"),
    ES("😗", "kissing face affection love peck smooch"),
    ES("😙", "kissing face with smiling eyes happy kiss love affection"),
    ES("😚", "kissing face with closed eyes love shy romantic affection"),
    ES("😋", "face savoring food yum delicious tasty hungry"),
    ES("😛", "face with tongue playful silly teasing childish"),
    ES("😝", "squinting face with tongue silly goofy crazy wild"),
    ES("😜", "winking face with tongue silly crazy wild mischievous playful"),
    ES("🤪", "zany face goofy silly crazy wild wacky"),
    ES("🤨", "face with raised eyebrow skeptical suspicious questioning doubtful"),
    ES("🧐", "face with monocle sophisticated curious examining skeptical"),
    ES("🤓", "nerd face geek smart intelligent bookworm glasses"),
    ES("😎", "smiling face with sunglasses cool confident awesome chill"),
    ES("🥸", "disguised face incognito hidden spy undercover secret"),
    ES("🤩", "star-struck excited fan idol amazing wow"),
    ES("🥳", "partying face celebration birthday festive fun hooray"),
    ES("🙂‍↕️", "face up-down flipping uncertain mixed feelings"),
    ES("😏", "smirking face flirty suggestive smug knowing"),
    ES("😒", "unamused face unhappy disappointed annoyed side-eye"),
    ES("🙂‍↔️", "face left-right confused uncertain undecided"),
    ES("😞", "disappointed face sad unhappy upset let down"),
    ES("😟", "worried face concerned nervous anxious troubled"),
    ES("😕", "confused face puzzled perplexed uncertain unsure"),
    ES("🙁", "slightly frowning face disappointed sad upset"),
    ES("☹️", "frowning face sad upset unhappy concerned"),
    ES("😣", "persevering face struggling enduring patient determined"),
    ES("😖", "confounded face frustrated confused exasperated"),
    ES("😩", "weary face tired exhausted frustrated fed up"),
    ES("🥺", "pleading face begging puppy eyes emotional soft"),
    ES("😢", "crying face sad tears unhappy upset sob"),
    ES("😭", "loudly crying face sobbing wailing bawling heartbroken"),
    ES("😤", "face with steam from nose angry mad frustrated proud"),
    ES("😠", "angry face mad furious upset annoyed"),
    ES("😡", "pouting face mad angry rage furious"),
    ES("🤬", "face with symbols on mouth cursing swearing furious"),
    ES("🤯", "exploding head shocked amazed mind blown astonished"),
    ES("😳", "flushed face surprised embarrassed shocked blushing"),
    ES("🥵", "hot face heat sweating overheated fever burning"),
    ES("🥶", "cold face freezing ice winter shivering frozen"),
    ES("😶‍🌫", "face in clouds smoke foggy high confused head in clouds"),
    ES("😱", "face screaming in fear terrified scared horrified shock"),
    ES("😨", "fearful face scared afraid worried nervous"),
    ES("😰", "anxious face with sweat nervous worried tense stressed"),
    ES("😥", "sad but relieved face disappointed comforted consoled"),
    ES("😓", "downcast face with sweat stressed sad tired exhausted"),
    ES("🤗", "hugging face hug embrace support comfort"),
    ES("🤔", "thinking face hmm curious contemplating pondering"),
    ES("🫣", "face with peeking eye curious shy secretive sneaky"),
    ES("🤭", "face with hand over mouth oops giggle surprise secret"),
    ES("🫢", "face with open eyes and hand over mouth shock surprise secret"),
    ES("🫡", "saluting face respect military reporting duty"),
    ES("🤫", "shushing face quiet silence shhh whisper"),
    ES("🫠", "melting face hot overwhelmed relaxed giving up"),
    ES("🤥", "lying face liar fib dishonest deceptive pinocchio"),
    ES("😶", "face without mouth speechless silent quiet blank"),
    ES("🫥", "dotted line face invisible hidden disappearing vanished"),
    ES("😐", "neutral face blank expressionless indifferent straight-faced"),
    ES("🫤", "face with diagonal mouth skeptical mixed feelings uncertain"),
    ES("😑", "expressionless face blank meh indifferent emotionless"),
    ES("🫨", "shaking face earthquake trembling vibrating unstable"),
    ES("😬", "grimacing face awkward tense nervous yikes cringe"),
    ES("🙄", "face with rolling eyes annoyed frustrated whatever"),
    ES("😯", "hushed face surprised shock wow speechless"),
    ES("😦", "frowning face with open mouth shocked alarmed horrified"),
    ES("😧", "anguished face shocked horrified distressed worried"),
    ES("😮", "face with open mouth surprised amazed wow gasping"),
    ES("😲", "astonished face shocked surprised amazed stunned"),
    ES("🥱", "yawning face tired sleepy bored drowsy"),
    ES("😴", "sleeping face sleep snooze rest zzz"),
    ES("🤤", "drooling face hungry desire want appetite craving"),
    ES("😪", "sleepy face tired drowsy exhausted"),
    ES("😮‍💨", "face exhaling relief sigh tired exhausted"),
    ES("😵", "dizzy face confused disoriented faint"),
    ES("😵‍💫", "face with spiral eyes dizzy confused hypnotized"),
    ES("🤐", "zipper-mouth face silent secret quiet confidential"),
    ES("🥴", "woozy face dizzy intoxicated drunk tipsy"),
    ES("🤢", "nauseated face sick ill disgusted queasy"),
    ES("🤮", "face vomiting sick throw up ill nauseous"),
    ES("🤧", "sneezing face sick sneeze cold allergy achoo"),
    ES("😷", "face with medical mask sick ill virus disease doctor"),
    ES("🤒", "face with thermometer sick fever ill temperature"),
    ES("🤕", "face with head-bandage hurt injury pain accident"),
    ES("🤑", "money-mouth face rich wealthy money cash win"),
    ES("🤠", "cowboy hat face rodeo western yeehaw howdy"),
    ES("😈", "smiling face with horns devil evil mischievous naughty"),
    ES("👿", "angry face with horns devil demon evil mad"),
    ES("👹", "ogre monster creature scary japanese"),
    ES("👺", "goblin creature angry monster evil japanese"),
    ES("🤡", "clown face circus comedy entertainment scary"),
    ES("💩", "pile of poo poop crap dung funny"),
    ES("👻", "ghost halloween spooky scary spirit supernatural"),
    ES("☠", "skull and crossbones death poison danger pirate"),
    ES("👽", "alien extraterrestrial UFO space otherworldly"),
    ES("👾", "alien monster space game arcade retro invader"),
    ES("🤖", "robot machine automation AI technology"),
    ES("🎃", "jack-o-lantern halloween pumpkin carved spooky"),
    ES("😺", "grinning cat happy feline pet animal"),
    ES("😸", "grinning cat with smiling eyes happy cat feline pet"),
    ES("😹", "cat with tears of joy laughing cat lol happy"),
    ES("😻", "smiling cat with heart-eyes love cat adore feline"),
    ES("😼", "cat with wry smile smirk sarcastic feline"),
    ES("😽", "kissing cat love affection feline pet"),
    ES("🙀", "weary cat scared surprised shocked afraid feline"),
    ES("😿", "crying cat sad upset tears unhappy feline"),
    ES("😾", "pouting cat angry mad annoyed grumpy feline"),

    // Gestures 
    EG("🫶", "heart hands love care affection relationship support"),
    EG("🤲", "palms up together prayer beg plead request mercy"),
    EG("👐", "open hands welcome embrace acceptance offering"),
    EG("🙌", "raising hands celebration hooray yay praise worship"),
    EG("👏", "clapping hands applause bravo congratulations appreciation"),
    EG("🤝", "handshake deal agreement meeting greet partner business"),
    EG("👍", "thumbs up approve like good yes agree positive"),
    EG("👎", "thumbs down disapprove dislike bad no disagree negative"),
    EG("👊", "oncoming fist bump punch power solidarity strong"),
    EG("✊", "raised fist power strength resistance solidarity protest"),
    EG("🤛", "left-facing fist bump greeting solidarity leftward"),
    EG("🤜", "right-facing fist bump greeting solidarity rightward"),
    EG("🫷", "rightwards pushing hand move reject refuse push away"),
    EG("🫸", "leftwards pushing hand move reject refuse push away"),
    EG("🤞", "crossed fingers luck hope wish liar promise"),
    EG("✌️", "victory hand peace v sign scissors two"),
    EG("🫰", "hand with index finger and thumb crossed money cash payment"),
    EG("🤟", "love-you gesture rock ILY ASL sign language"),
    EG("🤘", "sign of the horns rock metal music concert cool"),
    EG("👌", "OK hand perfect good approval agree excellent"),
    EG("🤌", "pinched fingers italian hand gesture what do you want"),
    EG("🤏", "pinching hand small tiny little bit almost there"),
    EG("🫳", "palm down hand drop give place put"),
    EG("🫴", "palm up hand hold carry receive offer lift"),
    EG("👈", "backhand index pointing left direction here look"),
    EG("👉", "backhand index pointing right direction here look"),
    EG("👆", "backhand index pointing up direction here look above"),
    EG("👇", "backhand index pointing down direction here look below"),
    EG("☝️", "index pointing up attention important one moment wait"),
    EG("✋", "raised hand high five stop halt wait"),
    EG("🤚", "raised back of hand wave greeting volunteering"),
    EG("🖐", "hand with fingers splayed stop high five spread"),
    EG("🖖", "vulcan salute star trek spock live long prosper"),
    EG("👋", "waving hand hello goodbye hi greetings"),
    EG("🤙", "call me hand phone contact surf shaka hang loose"),
    EG("🫲", "leftwards hand reach give receive pass"),
    EG("🫱", "rightwards hand reach give receive pass"),
    EG("💪", "flexed biceps strong strength muscle gym power workout"),
    EG("🦾", "mechanical arm robot prosthetic strength cyborg"),
    EG("🖕", "middle finger rude offensive swear curse angry"),
    EG("✍️", "writing hand write note draw signature author"),
    EG("🙏", "folded hands please thank you pray beg hope wish"),
    EG("🫵", "index pointing at the viewer you point direct choose"),
    EG("🦶", "foot walking run kick toe sole"),
    EG("🦵", "leg kick walking running standing limb"),
    EG("🦿", "mechanical leg prosthetic robot artificial limb"),
    EG("💄", "lipstick makeup cosmetic beauty fashion"),
    EG("💋", "kiss mark love affection lips romance xoxo"),
    EG("👄", "mouth lips speak talk kiss eat"),
    EG("🫦", "biting lip flirt tease nervous anxious sexy"),
    EG("🦷", "tooth dentist smile mouth hygiene dental"),
    EG("👅", "tongue taste lick speak eat flavor"),
    EG("👂", "ear hear listen sound music"),
    EG("🦻", "ear with hearing aid deaf accessibility sound hearing"),
    EG("👃", "nose smell scent breathe sniff"),
    EG("👣", "footprints walking steps tracks trail path"),
    EG("👁", "eye look see vision sight watch"),
    EG("👀", "eyes look watch see stare peek"),
    EG("🫀", "anatomical heart organ human body medical health"),
    EG("🫁", "lungs breathing organ human body medical health"),
    EG("🧠", "brain mind thinking intelligence smart memory"),

    // People emojis
    EP("🗣", "speaking head talk chat speak voice announce"),
    EP("👤", "bust in silhouette person user profile shadow"),
    EP("👥", "busts in silhouette people users group shadow team"),
    EP("🫂", "people hugging embrace comfort support friends"),
    EP("👶", "baby infant newborn child young toddler"),
    EP("👧", "girl child young female kid daughter"),
    EP("🧒", "child young kid gender-neutral youth"),
    EP("👦", "boy child young male kid son"),
    EP("👩", "woman female adult person lady"),
    EP("🧑", "person adult gender-neutral human"),
    EP("👨", "man male adult person guy"),
    EP("👩‍🦱", "woman with curly hair female curls adult"),
    EP("🧑‍🦱", "person with curly hair curls gender-neutral adult"),
    EP("👨‍🦱", "man with curly hair male curls adult"),
    EP("👩‍🦰", "woman with red hair female redhead ginger adult"),
    EP("🧑‍🦰", "person with red hair redhead ginger gender-neutral"),
    EP("👨‍🦰", "man with red hair male redhead ginger adult"),
    EP("👱‍♀️", "woman with blonde hair female blonde hair adult"),
    EP("👱", "person with blonde hair blonde hair gender-neutral"),
    EP("👱‍♂️", "man with blonde hair male blonde hair adult"),
    EP("👩‍🦳", "woman with white hair female elderly gray hair adult"),
    EP("🧑‍🦳", "person with white hair elderly gray hair gender-neutral"),
    EP("👨‍🦳", "man with white hair male elderly gray hair adult"),
    EP("👩‍🦲", "woman with bald head female hairless adult"),
    EP("🧑‍🦲", "person with bald head gender-neutral hairless adult"),
    EP("👨‍🦲", "man with bald head male hairless adult"),
    EP("🧔‍♀️", "woman with beard female facial hair adult"),
    EP("🧔", "person with beard facial hair adult"),
    EP("🧔‍♂️", "man with beard male facial hair adult"),
    EP("👵", "old woman elderly female senior grandmother"),
    EP("🧓", "older person elderly senior gender-neutral adult"),
    EP("👴", "old man elderly male senior grandfather"),
    EP("👲", "person with skullcap hat cap male headwear"),
    EP("👳‍♀️", "woman wearing turban female headwear religious"),
    EP("👳", "person wearing turban headwear religious gender-neutral"),
    EP("👳‍♂️", "man wearing turban male headwear religious"),
    EP("🧕", "woman with headscarf hijab religious female"),
    EP("👮‍♀️", "woman police officer female cop law enforcement"),
    EP("👮", "police officer cop law enforcement gender-neutral"),
    EP("👮‍♂️", "man police officer male cop law enforcement"),
    EP("👷‍♀️", "woman construction worker female builder hard hat"),
    EP("👷", "construction worker builder hard hat gender-neutral"),
    EP("👷‍♂️", "man construction worker male builder hard hat"),
    EP("💂‍♀️", "woman guard female security royal uniform"),
    EP("💂", "guard security royal uniform gender-neutral"),
    EP("💂‍♂️", "man guard male security royal uniform"),
    EP("🕵️‍♀️", "woman detective female spy investigate"),
    EP("🕵️", "detective spy investigate gender-neutral sleuth"),
    EP("🕵️‍♂️", "man detective male spy investigate"),
    EP("👩‍⚕️", "woman health worker female doctor nurse medical"),
    EP("🧑‍⚕️", "health worker doctor nurse medical gender-neutral"),
    EP("👨‍⚕️", "man health worker male doctor nurse medical"),
    EP("👩‍🌾", "woman farmer female agriculture gardening"),
    EP("🧑‍🌾", "farmer agriculture gardening gender-neutral"),
    EP("👨‍🌾", "man farmer male agriculture gardening")
];